Add ShoppingCart model
4Vitalii5/online-book-store pull request #11
Opened 2024-10-24 14:00 UTC by 4Vitalii5

Spring Boot practice
At the end of this HW you should have an ability to add a certain book to your shopping cart, so you need to implement the missing functionality. Below you will see the detailed requirements what should be in your project.

User Use Cases (means these operations are allowed to users with role USER)
Use cases are the set of actions that could be performed by some actor (in this case user). Here are the list of use cases that we will cover in this part of HW:

Shopping Cart Management:

As a User, I want to add books to my shopping cart, so I can purchase them. I will:
Send a POST request to /api/cart to add a book to the shopping cart.
As a User, I want to view my shopping cart, so I can review its contents before placing an order. I will:
Send a GET request to /api/cart to retrieve my shopping cart.
As a User, I want to update the books quantity in my shopping cart, so I can update my intended purchases. I will:
Send a PUT request to /api/cart/items/{cartItemId} to update the books quantity in the shopping cart.
As a User, I want to remove books from my shopping cart, so I can update my intended purchases. I will:
Send a DELETE request to /api/cart/items/{cartItemId} to remove a book from the shopping cart.
Domain models (entities)
There is a list of all entities that should be present in the project after this HW:

Book: Represents a book available in the store.
User: Contains information about the registered user including their authentication details and personal information.
Role: Represents the role of a user in the system, for example, admin or user.
Category: Represents a category that a book can belong to.
ShoppingCart: Represents a user's shopping cart.
CartItem: Represents an item in a user's shopping cart.
ShoppingCart entity
ShoppingCart: Represents a user's shopping cart. You can use soft delete for shopping carts.

Add a new entity ShoppingCart with the next fields:
id (Long, PK)
user (User, not null)
cartItems (Set<CartItem>)
CartItem entity
CartItem: Represents an item in a user's shopping cart. You can avoid using soft delete for cart items and remove them permanently.

Add a new entity CartItem with the next fields:
id (Long, PK)
shoppingCart (ShoppingCart, not null)
book (Book, not null)
quantity (int, not null)
HINT: It may be helpful to add @Named("bookFromId") default Book bookFromId(Long id) { // your implementation here} to the BookMapper interface

2024-10-24 17:18 UTC, Elena-Bruyako requested changes
see comments

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/item/CreateCartItemRequestDto.java
> +        int quantity
int type can't be null

```suggestion
        @Positive
        Long bookId,
        @Positive
        int quantity
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/item/UpdateCartItemDto.java
> +        int quantity
```suggestion
        @Positive
        int quantity
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/user/UserLoginRequestDto.java
>          @NotEmpty
```suggestion
        @NotBlank
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/user/UserLoginRequestDto.java
>          @NotEmpty
```suggestion
        @NotBlank
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(getCurrentUserId());
```suggestion
        ShoppingCart shoppingCart = getShoppingCartByCurrentUser();
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(getCurrentUserId());
```suggestion
        ShoppingCart shoppingCart = getShoppingCartByCurrentUser();
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-10-24 17:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-10-25 06:16 UTC, liliia-ponomarenko approved these changes
awesome 😎

2024-10-25 06:16 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        }
better avoid if-else construction  
```suggestion
        if (existingCartItem.isPresent()) {
            int updatedQuantity = existingCartItem.get().getQuantity() + requestDto.quantity();
            existingCartItem.get().setQuantity(updatedQuantity);
            return;
        } 
            CartItem newCartItem = cartItemMapper.toEntity(requestDto);
            newCartItem.setBook(book);
            newCartItem.setShoppingCart(shoppingCart);
            shoppingCart.getCartItems().add(newCartItem);
            cartItemRepository.save(newCartItem);
```

2024-10-28 19:01 UTC, 4Vitalii5 commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        }
Thank you.

2024-10-28 19:01 UTC, merged