Add tests for a Book functionality
4Vitalii5/online-book-store pull request #14
Opened 2024-11-05 22:37 UTC by 4Vitalii5

Add test cases for Book and Category entities (repository, service, controller).
You should add at least one test case for each service and controller layer.
In general, you should have at least 50% lines test coverage for BookController, CategoryController, BookService, and CategoryService classes
Please add a screenshot with the test coverage result into the PR description
[https://snipboard.io/uadnK8.jpg](url)

2024-11-06 18:56 UTC, Elena-Bruyako requested changes
see comments, apply it for all tests

2024-11-06 18:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/book/BookDto.java
> +    public BookDto(Long id, String title, String author, String isbn, BigDecimal price,
Just use Lombok annotation instead

2024-11-06 18:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +    public Book(Long id, String title, String author, String isbn, BigDecimal price,
same here

2024-11-06 18:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Category.java
> +    public Category(Long id, String name, String description) {
same here

2024-11-06 18:56 UTC, Elena-Bruyako commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +    @Sql(scripts = {
replace scripts under test class

2024-11-06 18:56 UTC, Elena-Bruyako commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +        executionPhase = Sql.ExecutionPhase.BEFORE_TEST_CLASS)
minor comment BEFORE_TEST_CLASS is default phase, so you can avoid it

2024-11-08 18:23 UTC, okuzan approved these changes

2024-11-08 19:22 UTC, merged